version: "3"
services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - './:/srv/librotenado:cached'
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'

volumes:
  mongo: